# Generated by Django 4.2.30 on 2026-05-15 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "worklogs_worklog",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["task"], name="idx_worklog_task"),
                    models.Index(fields=["user"], name="idx_worklog_user"),
                    models.Index(fields=["date"], name="idx_worklog_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HourlyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_from", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rates",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "worklogs_hourlyrate",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_rate_user"),
                    models.Index(fields=["project"], name="idx_rate_project"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hourlyrate",
            constraint=models.UniqueConstraint(
                fields=("user", "project", "effective_from"),
                name="uk_user_project_rate",
            ),
        ),
    ]
