# Generated by Django 4.2.30 on 2026-05-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('tasks', '0002_alter_comment_options_alter_mention_options_and_more'),
        ('worklogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlyrate',
            options={'verbose_name': '工时费率', 'verbose_name_plural': '工时费率'},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'verbose_name': '工时记录', 'verbose_name_plural': '工时记录'},
        ),
        migrations.RemoveConstraint(
            model_name='hourlyrate',
            name='uk_user_project_rate',
        ),
        migrations.RemoveIndex(
            model_name='hourlyrate',
            name='idx_rate_user',
        ),
        migrations.RemoveIndex(
            model_name='hourlyrate',
            name='idx_rate_project',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='worklogs_wo_task_id_0fcfc6_idx',
            old_name='idx_worklog_task',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='worklogs_wo_user_id_b932f2_idx',
            old_name='idx_worklog_user',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            new_name='worklogs_wo_date_3c35d8_idx',
            old_name='idx_worklog_date',
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='effective_from',
            field=models.DateField(verbose_name='生效日期'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='projects.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每小时费率'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(verbose_name='工作日期'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='工作内容说明'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='工时(小时)'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlyrate',
            unique_together={('user', 'project', 'effective_from')},
        ),
    ]
