# Generated by Django 4.2.30 on 2026-05-15 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("status_change", "Status Change"),
                            ("comment", "Comment"),
                            ("deadline", "Deadline"),
                            ("mention", "Mention"),
                            ("project_invite", "Project Invite"),
                            ("sprint_start", "Sprint Start"),
                            ("sprint_end", "Sprint End"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("related_type", models.CharField(blank=True, max_length=50)),
                ("related_id", models.CharField(blank=True, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="idx_notif_user"),
                    models.Index(fields=["created_at"], name="idx_notif_created"),
                ],
            },
        ),
    ]
