# Generated by Django 4.2.30 on 2026-05-15 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notification_type', models.CharField(choices=[('task_assigned', '任务分配'), ('status_change', '状态变更'), ('comment', '评论'), ('deadline', '截止提醒'), ('mention', '提及'), ('project_invite', '项目邀请'), ('sprint_start', '冲刺开始'), ('sprint_end', '冲刺结束')], db_column='type', max_length=32, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_type', models.CharField(blank=True, help_text='如 Task / Project / Sprint', max_length=50, verbose_name='关联实体类型')),
                ('related_id', models.UUIDField(blank=True, null=True, verbose_name='关联实体 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'), models.Index(fields=['created_at'], name='idx_notif_created')],
            },
        ),
    ]
