# Generated by Django 4.2.30 on 2026-05-15 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sprints", "0001_initial"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tasks.comment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "tasks_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("milestone", "Milestone"),
                            ("bug", "Bug"),
                            ("epic", "Epic"),
                        ],
                        default="task",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Todo"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("done", "Done"),
                            ("blocked", "Blocked"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("progress", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "tasks_task",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="tasks.comment",
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks_mention",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tasks.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("precedes", "Precedes"),
                            ("relates_to", "Relates To"),
                        ],
                        default="precedes",
                        max_length=20,
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_deps",
                        to="tasks.task",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_deps",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "tasks_taskdependency",
                "indexes": [
                    models.Index(fields=["predecessor"], name="idx_dep_predecessor"),
                    models.Index(fields=["successor"], name="idx_dep_successor"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.UniqueConstraint(
                fields=("predecessor", "successor"), name="uk_dependency"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project"], name="idx_task_project"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["sprint"], name="idx_task_sprint"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["assignee"], name="idx_task_assignee"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="idx_task_status"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="idx_task_priority"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent_task"], name="idx_task_parent"),
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.UniqueConstraint(
                fields=("comment", "mentioned_user"), name="uk_mention"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["task"], name="idx_comment_task"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["project"], name="idx_comment_project"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["author"], name="idx_comment_author"),
        ),
    ]
