# Generated by Django 4.2.30 on 2026-05-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('sprints', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='mention',
            options={'verbose_name': '@提及', 'verbose_name_plural': '@提及'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='taskdependency',
            options={'verbose_name': '任务依赖', 'verbose_name_plural': '任务依赖'},
        ),
        migrations.RemoveConstraint(
            model_name='mention',
            name='uk_mention',
        ),
        migrations.RemoveConstraint(
            model_name='taskdependency',
            name='uk_dependency',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='idx_comment_task',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='idx_comment_project',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='idx_comment_author',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='idx_task_sprint',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='idx_task_priority',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='idx_task_parent',
        ),
        migrations.RemoveIndex(
            model_name='taskdependency',
            name='idx_dep_predecessor',
        ),
        migrations.RemoveIndex(
            model_name='taskdependency',
            name='idx_dep_successor',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_project_4035b9_idx',
            old_name='idx_task_project',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_assigne_a1ddb3_idx',
            old_name='idx_task_assignee',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_4a0a95_idx',
            old_name='idx_task_status',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tasks.comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='tasks.comment', verbose_name='所属评论'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mention',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='已读状态'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL, verbose_name='被提及用户'),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='实际工时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='预估工时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.task', verbose_name='父任务'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度(%)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sprints.sprint', verbose_name='所属冲刺'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('milestone', 'Milestone'), ('bug', 'Bug'), ('epic', 'Epic')], default='task', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='predecessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='tasks.task', verbose_name='前驱任务'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='relation_type',
            field=models.CharField(choices=[('blocks', 'Blocks'), ('precedes', 'Precedes'), ('relates_to', 'Relates To')], default='precedes', max_length=20, verbose_name='关系类型'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='successor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='tasks.task', verbose_name='后继任务'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('predecessor', 'successor')},
        ),
    ]
