# Generated by Django 4.2.30 on 2026-05-15 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("version", "Version"),
                            ("sub_project", "Sub Project"),
                        ],
                        default="team",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_boards",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "kanban_kanbanboard",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KanbanColumn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("wip_limit", models.IntegerField(default=0)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="kanban.kanbanboard",
                    ),
                ),
            ],
            options={
                "db_table": "kanban_kanbancolumn",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TaskColumn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("order", models.IntegerField(default=0)),
                ("moved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_columns",
                        to="kanban.kanbancolumn",
                    ),
                ),
            ],
            options={
                "db_table": "kanban_taskcolumn",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="taskcolumn",
            constraint=models.UniqueConstraint(
                fields=("task_id", "column"), name="uk_task_column"
            ),
        ),
        migrations.AddIndex(
            model_name="kanbancolumn",
            index=models.Index(
                fields=["board", "order"], name="idx_column_board_order"
            ),
        ),
        migrations.AddIndex(
            model_name="kanbanboard",
            index=models.Index(fields=["project"], name="idx_board_project"),
        ),
    ]
